spring.application.name=ShufuRoom

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=${SUPABASE_ISSUER_URI}

eureka.client.enabled=false
spring.cloud.discovery.enabled=false

supabase.anon.key=${SUPABASE_ANON_KEY}

server.address=0.0.0.0
